config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  scope "/:locale" do    
    resources :sports, :only => [ :index, :show ] do
      resources :events, :only => [ :index, :show ] do
        resources :outcomes, :only => [ :index, :show ]
      end
    end
  end

end

app/models/betvictor_record.rb
class BetvictorRecord
  extend BetvictorConnection
  
  attr_reader :record

  def initialize record
    @record = record
  end
end

app/models/concerns/betvictor_connection.rb
module BetvictorConnection

  def attr_readable *args
    args.each do |arg|
      define_method( arg ) { record[ arg.to_s ] }
    end
  end

  def all *args
    retrieve_all_from_source( args ).map { |record| new record }
  end

  def find id, *args
    new retrieve_from_source id.to_i, args
  end

  def first
    all.first
  end

  def last
    all.last
  end

protected

  def retrieve_from_source id, args
    Betvictor.new.find name_symbol, id, args
  end

  def retrieve_all_from_source args
    Betvictor.new.send pluralized_name_symbol, args
  end

end

app/models/event.rb
class Event < BetvictorRecord
  attr_readable :id, :title, :is_virtual, :start_time, :meeting
end

app/models/outcome.rb
class Outcome < BetvictorRecord
  attr_readable :id, :description, :market, :price_decimal, :price
end

app/models/sport.rb
class Sport < BetvictorRecord
  attr_readable :id, :title, :meetings, :is_virtual, :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

private

  def set_locale
    I18n.locale = params[ :locale ] if params[ :locale ].present?
  end

  def default_url_options options = {}
    { locale: I18n.locale }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all params[ :sport_id ]
  end

  def show
    @event = Event.find params[ :id ], params[ :sport_id ]
  end
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  def index
    @outcomes = Outcome.all params[ :sport_id ], params[ :event_id ]
  end

  def show
    @outcome = Outcome.find params[ :id ], params[ :sport_id ], params[ :event_id ]
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.all
  end

  def show
    @sport = Sport.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_boolean bool
    bool ? I18n.t( 'helpers.yes_helper' ) : I18n.t( 'helpers.no_helper' )
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/events/_event.html.erb
<ul>
  <li class="attribute">
    <span><%= t( 'models.event.attributes.title' ) %>: </span>
    <span><%= link_to event.title, sport_event_path( params[ :sport_id ], event.id ) %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.event.attributes.start_time' ) %>: </span>
    <span><%= event.start_time %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.event.attributes.meeting' ) %>: </span>
    <span><%= event.meeting %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.event.attributes.is_virtual') %>: </span>
    <span><%= humanize_boolean event.is_virtual %></span>
  </li>
  <li> <%= link_to t( 'application.links.go_to_outcomes' ), sport_event_outcomes_path( params[ :sport_id ], event.id ) %> </li>
</ul>

app/views/events/index.html.erb
<h2> <%= t( "models.event.name" ).pluralize %> </h2>

<ul id="event_list" >
  <% @events.each do |event| %>
    <li class="event" id="event_#{event.id}">
      <%= render partial: 'event', :locals => { :event => event } %>
    </li>
  <% end %>
</ul>

<%= link_to t( "application.links.back_to_sport" ), sport_path( params[ :sport_id] ) %> 

app/views/events/show.html.erb
<%= render partial: 'event', :locals => { :event => @event } %>

<%= link_to t( 'application.links.back_to_events' ), sport_events_path( params[ :sport_id ] ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetvictorInterview</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/outcomes/_outcome.html.erb
<ul>
  <li class="attribute">
    <span><%= t( 'models.outcome.attributes.description' ) %>: </span>
    <span><%= link_to outcome.description, sport_event_outcome_path( params[ :sport_id ], params[ :event_id ], outcome.id ) %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.outcome.attributes.market') %>: </span>
    <span><%= outcome.market %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.outcome.attributes.price_decimal') %>: </span>
    <span><%= outcome.price_decimal %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.outcome.attributes.price') %>: </span>
    <span><%= outcome.price %></span>
  </li>
</ul>

app/views/outcomes/index.html.erb
<h2> <%= t( "models.outcome.name" ).pluralize %> </h2>

<ul id="outcome_list" >
  <% @outcomes.each do |outcome| %>
    <li class="outcome" id="outcome_#{outcome.id}">
      <%= render partial: 'outcome', :locals => { :outcome => outcome } %>
    </li>
  <% end %>
</ul>

<%= link_to t( "application.links.back_to_event" ), sport_event_path( params[ :sport_id ], params[ :event_id ] ) %> 

app/views/outcomes/show.html.erb
<%= render partial: 'outcome', :locals => { :outcome => @outcome } %>

<%= link_to t( 'application.links.back_to_outcomes' ), sport_event_outcomes_path( params[ :sport_id ], params[ :event_id ] ) %>

app/views/sports/_sport.html.erb
<ul>
  <li class="attribute">
    <span><%= t( 'models.sport.attributes.title' ) %>: </span>
    <span><%= link_to sport.title, sport_path( sport.id ) %></span>
  </li>
  <li class="attribute">
    <span><%= t( 'models.sport.attributes.is_virtual') %>: </span>
    <span><%= humanize_boolean sport.is_virtual %></span>
  </li>
  <li> <%= link_to t( 'application.links.go_to_events' ), sport_events_path( sport.id ) %> </li>
</ul>

app/views/sports/index.html.erb
<h2> <%= t( "models.sport.name" ).pluralize %> </h2>

<ul id="sport_list" >
  <% @sports.each do |sport| %>
    <li class="sport" id="sport_#{sport.id}">
      <%= render partial: 'sport', :locals => { :sport => sport } %>
    </li>
  <% end %>
</ul>

app/views/sports/show.html.erb
<%= render partial: 'sport', :locals => { :sport => @sport } %>

<%= link_to t( 'application.links.back_to_index' ), sports_path %>

app/views/welcome/index.html.erb
<h2> Choose a language </h2>

<%= link_to 'English', sports_path %>
<%= link_to 'Español', sports_path( :locale => 'es' ) %>